### ISSUE TITLE
You should probably delete this project

### ISSUE THREAD

**Issue by jimidle** [UpLibs/tree_component#1]
Respectfully,

It seems that you are not going to complete this project, so perhaps you would be kind enough to delete it so that people looking for a dart tree component will not try to use it. 
- It does not work as it stands - seems to be something wrong with how the library is set up.
- Your example code has syntax errors and won't compile RootNodeListener
- There is no working example

It would likely be better to delete the project and not have people wasting time trying to use it.

**Comment by gmpassos** [comment]
One of the main ideas of any open source project is to receive collaboration of many developers around the world. This project is open and free for anyone that want to use it, including to fix it and improve it. Thanks for your help, specially pointing what should be fixed. We are still waiting for free collaborations to fix what you have pointed. Best regards.
